trigger:
- main

pool:
  name: Default

steps:
- task: DockerInstaller@0

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'muhammadaleem/aleem-sample-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
