trigger:
- main

pool:
  name: 'AleemSelfHostedAgent'

steps:
- task: DockerInstaller@0

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'muhammadaleem/aleem-sample-app'
    command: 'buildAndPush'
    Dockerfile: 'node-js-sample/Dockerfile'
    tags: 'latest'
